### ISSUE TITLE
Examples in README didn't work

### ISSUE THREAD

**Issue by fengsy868** [patverga/torch-relation-extraction#3]
Hello,

As in the README, there has 

> 3. Now we want to train a model. Edit the example lstm config to say export TRAIN_FILE=train-mtx.torch and start the model training : ./bin/train/train-model.sh 0 bin/train/configs/lstm-example. This will save a model to models/lstm-example/*-model every 3 epochs.

In fact, follow this command won't generate the models trained, I believe we should add the $SAVE_MODEL to 1 to enable save the MODELs

**Comment by patverga** [comment]
You're right, I went ahead and fixed this. Thanks for pointing it out.
