### ISSUE TITLE
Examples without using GPU didn't work

### ISSUE THREAD

**Issue by fengsy868** [patverga/torch-relation-extraction#4]
Hi,

I try to follow your examples, but I don't have GPU on my computer so I set `-gpuid -1`. But, when I run the scoring program, it has some bug about 
`Invalid parameter: floatTensor
Expected: DoubleTensor`

so I modified a little the code and it runs. But the result failed to give me a score.

My candidate file is like:
`Barack Obama    per:spouse      Michelle Obama  doc_info        0       2       8       10      Barack Obama was seen yesterday with his wife Michelle Obama`

output is:
`Barack Obama    per:spouse      Michelle Obama  doc_info        0       2       8       10      nan`

Could you help me?

**Comment by patverga** [comment]
Hey I'm not sure exactly where the issue is. Can you paste the full stack trace? I will take a look once I get it.

**Comment by patverga** [comment]
It seems like this was due to a Lua version mismatch. Added requirement of Lua 5.1 to readme.
